name: Backend CI

on:

  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Python Syntax Check
        run: |
          python -m py_compile $(find backend -name "*.py")